# Generated by Django 4.2.3 on 2023-07-15 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taalim', '0004_alter_course_credit_hours_alter_program_credit_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taalim.course')),
                ('students', models.ManyToManyField(related_name='enrolled_in', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
