# Generated by Django 4.2.3 on 2023-07-15 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taalim', '0006_classattendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classattendance',
            name='student_id',
        ),
        migrations.AddField(
            model_name='classattendance',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attends', to=settings.AUTH_USER_MODEL),
        ),
    ]
