# Generated by Django 4.2.3 on 2023-07-15 14:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taalim', '0007_remove_classattendance_student_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classattendance',
            name='student_id',
        ),
        migrations.AddField(
            model_name='classattendance',
            name='student_id',
            field=models.ManyToManyField(related_name='attends', to=settings.AUTH_USER_MODEL),
        ),
    ]
