# Generated by Django 4.2.3 on 2023-07-17 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taalim', '0009_semester_semesterresult_remove_courseclass_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseresult',
            name='student',
            field=models.ForeignKey(limit_choices_to={'is_student': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
