# Generated by Django 4.2.3 on 2023-07-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taalim', '0010_alter_courseresult_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='uploads/avatar.jpg', null=True, upload_to=''),
        ),
    ]
