# Generated by Django 4.2.3 on 2023-07-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taalim', '0011_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='avatar.jpg', null=True, upload_to=''),
        ),
    ]
