# Generated by Django 4.2.3 on 2023-07-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taalim', '0013_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='offered_in', to='taalim.course'),
        ),
    ]
