# Generated by Django 4.2.3 on 2023-07-26 06:48

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('taalim', '0014_alter_semester_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseresult',
            name='course',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='instructor', chained_model_field='instructor', on_delete=django.db.models.deletion.CASCADE, to='taalim.course'),
        ),
    ]
