# Generated by Django 4.2.3 on 2023-07-26 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taalim', '0015_alter_courseresult_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseresult',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taalim.course'),
        ),
    ]
