# Generated by Django 4.2.3 on 2023-07-26 08:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taalim', '0016_alter_courseresult_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_student': True}, related_name='enrolled_in', to=settings.AUTH_USER_MODEL),
        ),
    ]
