# Generated by Django 4.2.3 on 2023-07-26 09:03

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('taalim', '0017_course_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseresult',
            name='course',
        ),
        migrations.AddField(
            model_name='courseresult',
            name='course',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='student', chained_model_field='students', to='taalim.course'),
        ),
    ]
