# Generated by Django 4.2.3 on 2023-07-26 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taalim', '0018_remove_courseresult_course_courseresult_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseresult',
            name='course',
        ),
        migrations.AddField(
            model_name='courseresult',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taalim.course'),
        ),
    ]
