# Generated by Django 4.2.3 on 2023-07-26 10:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taalim', '0019_remove_courseresult_course_courseresult_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseresult',
            name='gpa',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
